#bodyCell {
    padding-top: 20px;
}
.notifications {
    display: none;
}
.cell-action {
    width: 60px;
    text-align: center;
}
.cell-subscribe {
    width: 60px;
}
.cell-name {
    width: 150px;
}
.cell-name input {
    width: 100%;
}
.cell-query input {
    width: 100%;
}
.cell-api {
    width: 70px;
}
.cell-api input {
    width: 50px;
}
.cell-no {
    width: 120px;
}
.cell-nf {
    width: 100px;
}
.cell-desc input {
    width: 100%;
}